# Generated by Django 5.2.8 on 2025-12-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
