# Generated by Django 5.2.8 on 2025-12-14 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_contact_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 12, 14, 11, 10, 47, 790395, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 12, 14, 11, 11, 24, 784934, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
