# Generated by Django 5.2.8 on 2025-12-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_contact_created_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["created_date"]},
        ),
    ]
