# Generated by Django 5.2.8 on 2026-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
