# Generated by Django 5.2.8 on 2025-12-14 11:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2025, 12, 14, 11, 9, 43, 296691, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
