# Generated by Django 5.2.8 on 2025-12-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_alter_post_created_date_alter_post_updated_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="countent",
            new_name="content",
        ),
    ]
