# Generated by Django 5.2.8 on 2025-12-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog/default.jpg", upload_to="blog/"),
        ),
    ]
