# Generated by Django 5.2.8 on 2025-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0005_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="myblog.category"),
        ),
    ]
