# Generated by Django 5.2.8 on 2026-01-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0006_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_date"]},
        ),
    ]
