# Generated by Django 5.2.8 on 2026-02-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0009_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
    ]
