# Generated by Django 5.2.8 on 2026-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0010_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="login_require",
            field=models.BooleanField(default=False),
        ),
    ]
